object Runner {


  def main(args: Array[String]): Unit = {
    import com.binf.Fun._

    val d = distanceBetweenPatternAndString("ACTGCGT",
      Seq(
        "TAAAGTCACGGAGTTCGCACGGTAAAGGATAACCAGGAGTTCCTGAACCTAATAGGAGCTAGAACGGAAGGGCTAGCGCTCGTCCGGTCATGA",
          "GTAATGGCCAACGTCGTAATTTCCGTTTTTAAGGTTACACTTATTAACTCGATCTAGTGGGCCAAGCACGTTTCCCCTACTGTAACTAACAGT",
          "CCTGGGTACTCCAGACCTTGCATCTGCGTATTGTGGCTGGTAATAAAGGGTGTGGATAACTCAAGCTTGTGGTTGATATGCAGAGATGGGCCG",
          "CGACATTTCATGCCCGAACGGCTCACTCGCGTATTGCCGGTTCGGATTTTACCTTCTGTGCGATTTGGCCAATAGACTGAATTTGGTCCCTGT",
          "GGTAGGACGGCCTATTGGAGCCTACGCCCTACCCCCCTAGGGGCCGCGCTCGGCCAATGATCAATTGGACATCCCAGGCAAGAAAGAACTGCG",
          "CCGTATACCGCAGTCAGCACGATGCATGTGCCGGGTTACAGGATACGTTCTGAGCCGTGTGCAACATACCTAGGACCCACCTCGGTCTCATTT",
          "CAATAATCTTCAGTTGCAAGGCTTTAACTATGACATTCAAGTCGCGTTGCTCCGGTCGGGGCGGGGAGGGGTCTGGAAGCGAGCGCGTGCGCC",
          "ATCGGTAGAAACGAAACTGAAGCTTTGGTGGGTGTGATCCGGTCCAAGAAGCACGGTACTGGCCACTTTGCTGTTGGGGCCACCAACCCCATG",
          "GTCATCTAGCAAGACAATATTGAGACTCATTGGGAGCATGGCTCATTCGAACCGCGGTGGCGAATTCAGTTCATGGACGCAAATATTTGTTGG",
          "CGCGGTATAGGCTCTCGGTTGGCTGCACTGGCATTAATCGGTCTGTATTGTGATGGAGGACAAGTAGGAAATCTACTTCCTGTAGTGGGCGCC",
          "CGTTCACCTAAAAGAAGTAGATTCCCATTTATAAGTACGTGTCAGGCTGTTATATTGTCCATTAAACGACGGTGTGCCCTTTCCCTACCAAGG",
          "GACCAGGATCTCTCGGGAACATAAACGCTCGATTGGACCTGTGATTGTAAAGAGTACGCTCGGGACTACGGCGGCTCGCGTTTGACCGCCAGT",
          "GGTAAAACCTCGTGTCTAGTTCAGAGGTCTTGGCCTAGGTGACTAAATGCAAGGAACATTAGGTAGGATCTTTCTTACTATGCTTAACGACAA",
          "AAAACCAGACATCATCCCCCCCTACCATTGAATCGGAAGGATCCGTGGGATCTCCGACGTTACTATGAACTAAGGGCCAGTACTGGGCTCTCA",
          "GCAGACTCTACCTGGACCTGATTCCATTTAAGCTGCGCAATATTGTATAATCTATGCTGCTGACACCACGATGATAAGGATGTTTCCAACGGC",
          "AGAACTCCACCCTCTTACCAATGAGGCCATCCGGTGCTTACCGTGTTGCTACGCTGCCGAATGATGGTAGGCCGAATAACTAAACACTATTCA",
          "ATGATCGTTGAACGGATAAATACTTCAACGCACCCTCACATGACAGCTGTTCTACCATCTAGCCGCGTTAAGGGTTTTGCAGATATTGCAATT",
          "GAGGATCCTTGCTCCCTGGCAGCGCGTCCGACGCCCGCAGCTAGTACTGATTCCCAGGAATAAAGGCGCGCTCAAATCCAAACATGATGACCC",
          "TAATATAACAACCACTGTACGGTCTAGTGGACCAAGGCATGGCGGGGACGTGCAGCAAAAATTGTCGTCGCCAATGCAATCAAGCTTCGGACA",
          "ATCTCTTCGCTATGAGATTAGTTTCCTAACACTTGTTGCCTGGAGAGGAGATCCGACCACACCGCTCATACTTCAACGAAAGCTGTTCAGAGC",
          "GAGTATATTGCATATGGTTATACAGCCAGCAGCTTGAACGAAGATATCTGACCTCCTTGTCCCTGTCTGACTACCTGGTTAACTAGTGTTGGC",
          "GGGGGCGCTCGATTCGGTCCGACTAACTATTGGTTATCCATGGTGCCTTACCATTAGAAGCGACTTTAGCTGCAGCTGACACTGACGACGCTC",
          "TCGCCTAAGTCTTATCGCGTAAAAGGAATAGGGCGCGTGTTTAGCGCTTGGCTCATTCTAGATATTGAGCCATTTATCGGCCGCGGCCCTCAA",
          "CCCTTCCTAATTTTAAGGTGATTCTATCCGTGTCTGCTGGATTAGTGTGGGTCCAGCGGAGGTGGTGGTACTTGGCTAAGCGCGGGAGACTAC",
          "TTTTTCTGTTAGTGTTAAGGGGATACTTGCGGGTGTCCAGGTTGAGCGCTTGACTGCGCTGAAGTAAGAGCAAACTGGTCGTACAATAATCTC",
          "CGTTCGTGACCTACGATGAAAGATAAGGTAGTTTGATTAGGCAAAACCGCTCGTTTCCCCTATTTTTTGCAGGCTGCTGGATGCGCTAGGGGC",
          "CTCATTAATGTATTGCACAACGCGGACAAAGCAGTACCTAACTCCGGTCGCTCGATATACCATTTCAGGTATCCACGTGACGTTTCACTAAGG",
          "GAGTGCTACGCTTGTTTAGATCTAGTTTCGAATAGCTATAGGTGACAAAGTAGGCAACTATGATTGACTCGATCAGGAGGCGCTTGCGCAAGT",
          "GCGTACATTTACCATGCGTAAGTTAATACCAACAACCAGAGTAAATCCACTCGACTGCCCCACCTCCCAGACCAACTCAATGTAACATATCTA",
          "CTATTCCTCCGTCTTTATACGCTATGCATTACGAAAGGCACCCCGGCTCAAAAACCGCGGGATCAGCTCGCGAGAGTCCCCACCCGGCACGTG"
        ) )
    println(d)

    //val result = neighbors("GAAGCACGGTC", 2)
    //println(result.mkString(" "))
    //val filePath = "/Users/pavel/Sources/bif/dna-analysis/src/main/resources/data/salmonella.txt"
    //val genome : String = scala.io.Source.fromFile(filePath)
    //  .getLines().toList.tails.mkString("")
    //val res = skewMin(genome)
    //val res : List[String] = freqWordsWithMismatches("ACGTTGCATGTCGCATGATGCATGAGAGCT", 4, 1, true)
    //println( res.distinct.mkString(" ") )
  }

}
