object Runner {


  def main(args: Array[String]): Unit = {
    import com.binf.Fun._

    val matrix = Array(
      Array(0.132, 0.237, 0.25, 0.303, 0.303, 0.263, 0.368, 0.211, 0.224, 0.303, 0.303, 0.25, 0.276),
      Array(0.316, 0.211, 0.329, 0.184, 0.289, 0.25, 0.263, 0.158, 0.237, 0.211, 0.25, 0.289, 0.184),
      Array(0.237, 0.276, 0.25, 0.184, 0.263, 0.263, 0.25, 0.276, 0.237, 0.289, 0.197, 0.276, 0.224),
      Array(0.316, 0.276, 0.171, 0.329, 0.145, 0.224, 0.118, 0.355, 0.303, 0.197, 0.25, 0.184, 0.316)
    )
    val result = profileMostProbableKmer("GCCGGGGGGTGATGCGCTAAGACGGGACCCTATTGGGGCATACCGTCATCCATATAGGCAGCCCGCTGTCGTCTGTACTTGTTCGCAAAGCGAGCGCCGCGGAGAACACAGTTAACAAATGTAGACTAATGGATAAGTCTACACAATGAAAGGTTGCCCACCCACGAGCGGAACGTACAACTAGTATGACCGTAAGTCTCTCTCGCAATAGCCAACTCCCATACACTTCGTGTTCCTTAGTGCAAAGCAATTGCGTGCTAAATTCGCGATCCTATTGTTGGTTTTTTTCGTTCCACCAGCACTAGAGCTTTGACAGAATGTATCGCAGCACGATTTTTCTTAACTTTACTTGTTTGCGGACAGACAATCCATGCTTCTACCAAAGGGCCACTCAATACGAGGATGCCAAACTGGGTCGCCGCACTGTATAGACGCTGTCCCGGATGAACGGAGCTGCAGATTCGCCGTGAGAAGCTACGCCTAATGCGTCTATTCTGCCTGCGCTCAATCTGGCTGACTGTGCAGGCAGCCCACAGGCTGTATTAAGATACGGTGTAGGACGACGAGTTAGCTAAAAATACTACCGTTCGATTACGTTAGCCTAAACCTCGGAAGTTATAGGAATCTCCGGTGTATGAACTCCCGCAAGTTTCGTGCGTAACGCGGCCCACCCAGGCCCACTTTATTTGTCATTTTTCAGTTCTGCTCGTTCAGCTGCGCGGACGGTCGACGAGACGTATAGGCCGGGAGCCCTGCCCGGTAATCGTTAGATTCTTACCCTTCGAGTGTACTATAATTAGTGACCAGAGTCTATCATTCAAACTTGTGCATCTGTGATACCTGAGCGGTTTGGCTTGACCGATGAACGTTCTACAAGCAAACCCGTAAGAAGGAAGTGGGACTATTCTGGAGCTGTTAACGACCCGGTTAGGGGTAAGTTAGGTGAATGGGACTCGTACTCAGAGGGAGGAGTTGCAATCCGCTAATACGTCCACGATAT", 13, matrix)
    println(result)
    //val result = neighbors("GAAGCACGGTC", 2)
    //println(result.mkString(" "))
    //val filePath = "/Users/pavel/Sources/bif/dna-analysis/src/main/resources/data/salmonella.txt"
    //val genome : String = scala.io.Source.fromFile(filePath)
    //  .getLines().toList.tails.mkString("")
    //val res = skewMin(genome)
    //val res : List[String] = freqWordsWithMismatches("ACGTTGCATGTCGCATGATGCATGAGAGCT", 4, 1, true)
    //println( res.distinct.mkString(" ") )
  }

}
